apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk   # "rootpassword" en base64
  mysql-database: dHdlZXRz               # "tweets" en base64
  mysql-user: dHdlZXR1c2Vy               # "tweetuser" en base64
  mysql-password: dHdlZXRwYXNz           # "tweetpass" en base64