apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306        # port du service à l'intérieur du cluster
      targetPort: 3306  # port du conteneur MySQL